const char* customHtml =
"<!DOCTYPE html>"
"<meta charset=\"utf-8\" />"
"<title>WebSocket Test</title>"
""
"<script language=\"javascript\" type=\"text/javascript\">"
""
"var url = \"ws://192.168.4.1:81/\";"
"var output;"
"var buttonH;"
"var buttonW;"
"var buttonT;"
"var canvasH;"
"var canvasW;"
"var context;"
""
""
"function init() {"
""
"    buttonH = document.getElementById(\"toggleButtonHold\");"
"    buttonW = document.getElementById(\"toggleButtonWrite\");"
"    buttonT = document.getElementById(\"BottonTest\");"
"    output = document.getElementById(\"output\");"
"    canvas = document.getElementById(\"ledH\");"
""    
"    contextH = canvas.getContext(\"2d\");"
"    contextH.arc(25, 25, 15, 0, Math.PI * 2, false);"
"    contextH.lineWidth = 3;"
"    contextH.strokeStyle = \"black\";"
"    contextH.stroke();"
"    contextH.fillStyle = \"black\";"
"    contextH.fill();"
"    canvas = document.getElementById(\"ledW\");"
"    contextW = canvas.getContext(\"2d\");"
"    contextW.arc(25, 25, 15, 0, Math.PI * 2, false);"
"    contextW.lineWidth = 3;"
"    contextW.strokeStyle = \"black\";"
"    contextW.stroke();"
"    contextW.fillStyle = \"black\";"
"    contextW.fill();"
""    
"    wsConnect(url);"
"}"
""
"function wsConnect(url) {"
""    
"    websocket = new WebSocket(url);"
""    
"    websocket.onopen = function(evt) { onOpen(evt) };"
"    websocket.onclose = function(evt) { onClose(evt) };"
"    websocket.onmessage = function(evt) { onMessage(evt) };"
"    websocket.onerror = function(evt) { onError(evt) };"
"}"
""
"function onOpen(evt) {"
""
"    console.log(\"Connected\");"
""   
"    buttonH.disabled = false;"
"    buttonW.disabled = false;"
""
"    doSend(\"getLEDState\");"
"}"
""
"function onClose(evt) {"
""
"    console.log(\"Disconnected\");"
""   
"    buttonH.disabled = true;"
"    buttonW.disabled = true;"
""    
"    setTimeout(function() { wsConnect(url) }, 2000);"
"}"
""
"function onMessage(evt) {"
""
"    console.log(\"Received: \" + evt.data);"
""   
"    switch(evt.data) {"
"        case \"0\":"
"            console.log(\"LEDH is off\");"
"            contextH.fillStyle = \"black\";"
"            contextH.fill();"
"            output.append(\"Hold LOW\\n\");"
"            break;"
"        case \"1\":"
"            console.log(\"LEDH is on\");"
"            contextH.fillStyle = \"red\";"
"            contextH.fill();"
"            output.append(\"Hold HIGH\\n\");"
"            break;"
"        case \"2\":"
"            console.log(\"LEDW is off\");"
"            contextW.fillStyle = \"black\";"
"            contextW.fill();"
"            output.append(\"Write LOW\\n\");"
"            break;"
"        case \"3\":"
"            console.log(\"LEDW is on\");"
"            contextW.fillStyle = \"red\";"
"            contextW.fill();"
"            output.append(\"Write HIGH\\n\");"
"            break;"
"        default:"
"            break;"
"    }"
"}"
""
"function onError(evt) {"
"    console.log(\"ERROR: \" + evt.data);"
"}"
""
"function doSend(message) {"
"    console.log(\"Sending: \" + message);"
"    websocket.send(message);"
"}"
""
"function onPress1() {"
"   doSend(\"toggleHold\\n\");"
"}"
"function onPress2() {"
"   doSend(\"toggleWrite\\n\");"
"}"
"function onPress3() {"
"   doSend(\"TEST\\n\");"
"}"
""
"window.addEventListener(\"load\", init, false);"
""
"</script>"
""
"<h2>DEBUG PAGE</h2>"
""
"<table>"
"   <tr>"
"   <td><button id=\"toggleButtonHold\" onclick=\"onPress1()\" disabled>Toggle Hold</button></td>"
"   <td><button id=\"toggleButtonWrite\" onclick=\"onPress2()\" disabled>Toggle Write</button></td>"
"   <td><button id=\"ButtonTest\" onclick=\"onPress3()\">TEST</button></td>"
"   <td><canvas id=\"ledH\" width=\"50\" height=\"50\"></canvas></td>"
"   <td><canvas id=\"ledW\" width=\"50\" height=\"50\"></canvas></td>"
"	<td><textarea rows=20 cols=30 id=\"output\"></textarea></td>"
"   </tr>"
"</table>"
;